name: 'TypeScript Build'
description: 'Build TypeScript project using Bun'

inputs:
  bun-version:
    description: 'Bun version to use'
    required: false
    default: 'latest'
  working-directory:
    description: 'Directory containing package.json'
    required: false
    default: '.'
  build-command:
    description: 'Build command to run'
    required: false
    default: 'bun run build'

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: bun install

    - name: Build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.build-command }}
