name: 'Publish to Crates.io'
description: 'Publish a Rust crate to crates.io'

inputs:
  crate-name:
    description: '[string] The name of the crate to publish (from Cargo.toml)'
    required: true
  crate-path:
    description: '[string] Optional: Path to crate directory (e.g., crates/client). If empty, publishes from workspace root using -p flag.'
    required: false
    default: ''
  dry-run:
    description: "[boolean: 'true'/'false'] Run cargo publish --dry-run instead of actual publish"
    required: false
    default: 'false'
  cargo-registry-token:
    description: '[secret] Crates.io API token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Publish to crates.io
      shell: bash
      env:
        CARGO_REGISTRY_TOKEN: ${{ inputs.cargo-registry-token }}
      run: |
        if [ -n "${{ inputs.crate-path }}" ]; then
          # Publish from crate directory
          echo "Publishing ${{ inputs.crate-name }} from ${{ inputs.crate-path }}..."
          cd "${{ inputs.crate-path }}"
          if [ "${{ inputs.dry-run }}" == "true" ]; then
            cargo publish --dry-run
          else
            cargo publish
          fi
        else
          # Publish from workspace root using -p flag
          echo "Publishing ${{ inputs.crate-name }} from workspace root..."
          if [ "${{ inputs.dry-run }}" == "true" ]; then
            cargo publish --dry-run -p "${{ inputs.crate-name }}"
          else
            cargo publish -p "${{ inputs.crate-name }}"
          fi
        fi

