name: 'Check PR Labels'
description: 'Check PR labels and output flags for release decisions'

inputs:
  labels:
    description: 'JSON array of labels to check (e.g., ["github-release", "prerelease"])'
    required: true
  default-on-push:
    description: 'Comma-separated list of labels to default to true on direct push (no PR found)'
    required: false
    default: ''

outputs:
  labels:
    description: 'JSON object with boolean results for each checked label'
    value: ${{ steps.check-labels.outputs.labels }}

runs:
  using: 'composite'
  steps:
    - name: Check PR Labels
      id: check-labels
      uses: actions/github-script@v7
      with:
        script: |
          const defaultOnPush = '${{ inputs.default-on-push }}'.split(',').map(l => l.trim().toLowerCase()).filter(Boolean);
          const labelsToCheck = JSON.parse('${{ inputs.labels }}');
          
          let pr = null;
          let prLabels = [];
          
          if (context.eventName === 'pull_request') {
            pr = context.payload.pull_request;
            prLabels = (pr.labels || []).map(l => l.name.toLowerCase());
            console.log(`PR event: Found PR #${pr.number} with labels: ${prLabels.join(', ') || 'none'}`);
          } else {
            try {
              const { data: prs } = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'closed',
                base: context.ref.replace('refs/heads/', ''),
                sort: 'updated',
                direction: 'desc',
                per_page: 10
              });
              
              pr = prs.find(p => p.merge_commit_sha === context.sha);
              
              if (pr) {
                const { data: prWithLabels } = await github.rest.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number
                });
                prLabels = (prWithLabels.labels || []).map(l => l.name.toLowerCase());
                console.log(`Push event: Found merged PR #${pr.number} with labels: ${prLabels.join(', ') || 'none'}`);
              } else {
                console.log('No merged PR found for this commit.');
              }
            } catch (error) {
              console.log(`Error finding PR: ${error.message}`);
            }
          }
          
          const results = {};
          for (const label of labelsToCheck) {
            const labelLower = label.toLowerCase();
            let hasLabel = prLabels.includes(labelLower);
            if (!hasLabel && !pr && defaultOnPush.includes(labelLower)) {
              hasLabel = true;
            }
            results[labelLower] = hasLabel;
          }
          
          console.log('Label check results:', JSON.stringify(results));
          core.setOutput('labels', JSON.stringify(results));
          return results;
