name: 'Generate Release Info'
description: 'Generate version number and release notes using AI'

inputs:
  service-name:
    description: '[string] The name of the service (used in release notes)'
    required: true
  prerelease:
    description: "[boolean: 'true'/'false'] Whether this is a prerelease (appends -rc.N suffix)"
    required: false
    default: 'false'
  openai-api-key:
    description: '[secret] OpenAI API key for AI-powered version detection and notes'
    required: true

outputs:
  version:
    description: 'The determined version (e.g., 1.2.3 or 1.2.3-rc.5)'
    value: ${{ steps.version.outputs.final }}
  release_notes:
    description: 'AI-generated release notes in markdown'
    value: ${{ steps.ai-notes.outputs.final-message }}

runs:
  using: 'composite'
  steps:
    - name: Determine Version
      id: version-info
      uses: photon-hq/buildspace/.github/blocks/determine-publish-version@main
      with:
        prerelease: ${{ inputs.prerelease }}
        openai-api-key: ${{ inputs.openai-api-key }}

    - name: Set Version Output
      id: version
      shell: bash
      run: |
        echo "final=${{ steps.version-info.outputs.version }}" >> $GITHUB_OUTPUT

    - name: AI Generate Notes
      id: ai-notes
      uses: openai/codex-action@v1
      with:
        openai-api-key: ${{ inputs.openai-api-key }}
        prompt: |
          Generate release notes for ${{ inputs.service-name }} v${{ steps.version.outputs.final }}.
          Changes since v${{ steps.version-info.outputs.previous-version }} (current commit: ${{ github.sha }}).
          
          REQUIREMENTS:
          1. NO title - start with content directly
          2. Plain language - like explaining to a friend
          3. SHORT - 1-2 sentences per item
          4. Group: ## New Features, ## Bug Fixes, ## Improvement, if they exist. For example, 
          if there are no new features, bug fixes, or improvements, don't include them.
          5. Only include breaking changes if they exist
          6. Include commit SHAs if necessary. If the commit is large, don't include it.
          7. 1-2 emojis max for personality
          8. Code diffs ONLY if necessary. If the diff is large, don't include it. 
          
          The end goal is clear business technical writing that is easy to understand, use, and bring 
          delight to the user
